language:
 - python

python:
  - 3.6

install:
  - pip3 install -r api/requirements.txt
  - pip install coveralls

script:
  - nosetests
  - nose2 --with-coverage
  - coveralls

after_success:
  - coveralls

after_success:
  - coveralls