language:
 - python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database trackertest;' -U postgres
  - python3 Api/run_migration.py

script:
  - cd Api
  - nosetests --with-coverage --cover-package=app
  - coveralls

after_success:
  - coveralls

after_success:
  - coveralls