language:
 - python

python:
  - 3.6

install:
  - pip3 install -r api/requirements.txt
  - pip install coveralls

script:
  - nosetests
  - nosetests --with-coverage --cover-package=app
  - coveralls

after_success:
  - coveralls

after_success:
  - coveralls