language:
 - python

python:
  - 3.6

install:
  - pip install -r Api/requirements.txt
  - pip install coveralls

script:
  - cd Api
  - nosetests --with-coverage --cover-package=app
  - coveralls

after_success:
  - coveralls

after_success:
  - coveralls